export const invoices = [
  {
    id: 1,
    productName: "Macbook pro 13”",
    category: "Laptop",
    status: "delivered",
    date: "Mar 17, 2020",
    amount: "$2399.00",
    image: "/images/mac.png",
    varients: "2",
  },
  {
    id: 2,
    productName: "Apple Watch Ultra",
    category: "Watch",
    status: "pending",
    date: "Mar 17, 2020",
    amount: "$879.00",
    image: "/images/watch.png",
    varients: "1",
  },
  {
    id: 3,
    productName: "iPhone 15 Pro Max",
    category: "Smart Phone",
    status: "delivered",
    date: "Mar 17, 2020",
    amount: "$3999.00",
    image: "/images/phone.png",
    varients: "2",
  },
  {
    id: 4,
    productName: "iPad Pro 3rd Gen",
    category: "Electronics",
    status: "canceled",
    date: "Mar 17, 2020",
    amount: "$1699.00",
    image: "/images/ipad.png",
    varients: "2",
  },
  {
    id: 5,
    productName: "Airpods Pro 2nd Gen",
    category: "Accessories",
    status: "delivered",
    date: "Mar 17, 2020",
    amount: "$879.00",
    image: "/images/airpods.png",
    varients: "1",
  },
];
